### ISSUE TITLE
"Recently Added" jumps to end of list after 2nd page

### ISSUE THREAD

**Issue by btouellette** [tsquillario/Jamstash#211] opened 2015-04-13 16:25 UTC
I've had this issue for a while. The Recently Added page works for the first two pages but after I hit ">" a second time instead of going to the third page it jumps to some much much later page (the last page?).

**Comment by tsquillario** [comment] 2015-05-31 18:39
Yea, I noticed this one before. I'll take a look...

**Comment by Hyzual** [comment] 2015-07-14 17:34
Hi ! The newest Jamstash beta version (4.6.0) is out on http://beta.jamstash.com, could you give it a try and tell me if it fixes this issue ?
I've been unable to reproduce it on my end, and since I did some refactoring on the "Recently Added" page, I wonder if maybe it would be fixed ?

**Comment by btouellette** [comment] 2015-07-14 17:37
This is fixed for me on the current beta site. Thanks!

**Comment by Hyzual** [comment] 2015-07-14 22:54
Cool ! I'll close this issue then. :)

**Closed by Hyzual** 2015-07-14 22:54 UTC
