### ISSUE TITLE
Artist not shown

### ISSUE THREAD

**Issue by murphey02** [tsquillario/Jamstash#207] opened 2015-03-27 10:04 UTC
If I click on an artist (in the left artist pane), albums will show-up in a normal situation.
but if I Click an artist with only one album, no albums are showed.
(Same bug is in the Beta version)

**Comment by Hyzual** [comment] 2015-03-31 12:05
Hi,

I tried to reproduce this bug but couldn't, In my library the first level (which is displayed on the left artist pane) corresponds to genres and some of my genre folders only have one artist in them, and all of those display fine.
Could you please post a screenshot showing what happens ? Also, when you press the F12 key and go to the "Console" tab, are there any javascript errors ?
If so, could you please copy and paste the error(s) here as they will help me identify the source of the problem.

Thanks !

**Comment by murphey02** [comment] 2015-04-01 09:53
There is no Java Error in the Console:
This is what I do:
1. Click A-Z choosing 'E'
2. Click artist 'Eagles, the' => Get 2 Albums as result  (That's correct)
3. Click artist 'Edmunds, Dave' => the result of 'the Eagles'remain on screen' (has 1 album)
4. Click artist 'Elis' =>  Get 5 Albums as result  (That's correct)

Any sequence wil give the same result.

![image](https://cloud.githubusercontent.com/assets/11678114/6938687/a80fed22-d865-11e4-830b-aeb33d7865e9.png)

**Comment by Reubentrapdoor** [comment] 2015-04-08 15:38
I'm able to reproduce this bug as well with all artists with a single album. The javascript console in Chrome shows no errors (or other messages) when clicking on an artist, nor does my Madsonic logs. Nothing appears to happen at all.

Tried with Jamstash 4.4.0 and Madsonic 5.2.5420.20141215.0303 (Subsonic API: 1.6.0).

If you have any suggestions for debugging this I will gladly have a go since this has been driving me crazy for months.

**Comment by Hyzual** [comment] 2015-04-08 17:33
Thanks for the input, I'll give it a look this friday. I'll keep you posted on this.

**Comment by Hyzual** [comment] 2015-04-11 18:15
I tried again but still, it worked. Using http://jamstash.com (so v 4.4.0) and a test Subsonic 5.2.1 server, I could display a single album.

Could either of you please create me a "guest" account or whatever so I can try with your backend and music ?

![2015-04-11 20_07_16-jamstash](https://cloud.githubusercontent.com/assets/2051507/7102642/af230602-e086-11e4-9bdd-f9059335e73c.png)

**Comment by tsquillario** [comment] 2015-04-17 21:48
I just pushed an update to http://beta.jamstash.com, let me know if your issue is resolved.

**Comment by Reubentrapdoor** [comment] 2015-04-22 20:43
Thanks for looking into this, the issue seems to be resolved in the latest beta.

**Closed** 2015-04-24 22:47 UTC
